name: Build Rebel

inputs:
  artifact:
    description: Name of the artifact to be uploaded
  build-options:
    description: SCons build options
  build-mono:
    description: Build mono version
    type: boolean
    default: false
  use-build-cache:
    description: Use a build cache to make subsequent builds faster
    type: boolean
    default: true
  rebel-executable:
    # TODO: Replace with an output.
    # This input should not be needed.
    # We should be able to determine this, and return it to the caller.
    description: Filename of the binary that will be built

runs:
  using: composite
  steps:
    - name: Checkout Rebel Engine
      uses: actions/checkout@v4
      with:
        repository: RebelToolbox/RebelEngine
        path: RebelEngine

    - name: Install dependencies
      shell: bash
      run: |
        #Install dependencies
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          echo "::group::Installing Linux dependencies"
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
          build-essential         \
          g++-multilib            \
          pkg-config              \
          clang                   \
          lld                     \
          mingw-w64               \
          emscripten              \
          scons                   \
          libx11-dev              \
          libxcursor-dev          \
          libxinerama-dev         \
          libxrandr-dev           \
          libxi-dev               \
          libgl-dev               \
          libudev-dev             \
          libasound2-dev          \
          libpulse-dev            \
          libx11-dev:i386         \
          libxcursor-dev:i386     \
          libxinerama-dev:i386    \
          libxrandr-dev:i386      \
          libxi-dev:i386          \
          libgl-dev:i386          \
          libudev-dev:i386        \
          libasound2-dev:i386     \
          libpulse-dev:i386       \
          yasm
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          echo "::endgroup::"
        fi
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "::group::Installing Windows dependencies"
          python -m ensurepip --upgrade
          python -m pip install scons
          echo "::endgroup::"
        fi
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          echo "::group::Installing macOS dependencies"
          brew update
          brew install \
          scons        \
          yasm
          echo "::endgroup::"
        fi

    - name: Set environment variables
      shell: bash
      run: |
        #Setting environment variables
        if [[ "${{ inputs.use-build-cache }}" == "true" ]]; then
          echo "SCONS_CACHE=.scons-cache/" >> $GITHUB_ENV
        fi
        if [[ "${{ inputs.build-mono }}" == "true" ]]; then
          echo "MONO_ENABLED=module_mono_enabled=yes" >> $GITHUB_ENV
        fi

    - name: Setup SCons cache
      if: inputs.use-build-cache == 'true'
      uses: actions/cache@v4
      with:
        path: RebelEngine/${{ env.SCONS_CACHE }}
        key: ${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
        restore-keys: |
          ${{ github.job }}-${{ strategy.job-index }}-

    - name: Generate Mono Glue for Mono Builds
      if: inputs.build-mono == 'true'
      shell: bash
      working-directory: RebelEngine
      run: |
        #Generate Mono Glue for Mono Builds
        echo "::group::Building Rebel for generating Mono glue"
        scons -j2 ${{ inputs.build-options }} tools=yes $MONO_ENABLED mono_glue=no
        echo "::endgroup::"
        echo "::group::Generating Mono Glue"
        DRI_PRIME=0 xvfb-run bin/${{ inputs.rebel-executable }} --generate-mono-glue modules/mono/glue
        echo "::endgroup::"

    - name: Build Rebel
      shell: bash
      working-directory: RebelEngine
      run: |
        #Build Rebel
        echo "::group::Building Rebel"
        scons -j2 ${{ inputs.build-options }} $MONO_ENABLED
        echo "::endgroup::"
        echo "Build files:"
        ls -1 bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: RebelEngine/bin/${{ inputs.rebel-executable }}
        retention-days: 1
