name: Build Rebel

inputs:
  artifact:
    description: Name of the artifact to be uploaded
  build-options:
    description: SCons build options
  include-mono:
    description: Build Rebel with Mono module
    type: boolean
    default: false
  use-build-cache:
    description: Use a build cache to make subsequent builds faster
    type: boolean
    default: true
outputs:
  build-filename:
    description: Filename of the binary that was built
    value: ${{ steps.get-build-filename.outputs.filename }}

runs:
  using: composite
  steps:
    - name: Checkout Rebel Engine
      uses: actions/checkout@v5
      with:
        repository: RebelToolbox/RebelEngine
        path: RebelEngine

    - name: Install dependencies
      shell: bash
      run: |
        #Install dependencies
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          echo "::group::Installing Linux dependencies"
          sudo apt-get update
          sudo apt-get install -y \
          build-essential         \
          pkg-config              \
          clang                   \
          lld                     \
          mingw-w64               \
          mono-devel              \
          emscripten              \
          scons                   \
          libx11-dev              \
          libxcursor-dev          \
          libxinerama-dev         \
          libxrandr-dev           \
          libxi-dev               \
          libgl-dev               \
          libudev-dev             \
          libasound2-dev          \
          libpulse-dev            \
          yasm
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          echo "::endgroup::"
        fi
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "::group::Installing Windows dependencies"
          python -m ensurepip --upgrade
          python -m pip install scons
          echo "::endgroup::"
        fi
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          echo "::group::Installing macOS dependencies"
          python -m ensurepip --upgrade
          python -m pip install scons
          brew update
          brew install \
          mono-devel   \
          yasm
          echo "::endgroup::"
        fi

    - name: Set SCons cache environment variable
      if: inputs.use-build-cache == 'true'
      shell: bash
      run: |
        #Set SCons Cache Environment Variable
        echo "SCONS_CACHE=.scons-cache/" >> $GITHUB_ENV

    - name: Setup SCons cache
      if: inputs.use-build-cache == 'true'
      uses: actions/cache@v4
      with:
        path: RebelEngine/${{ env.SCONS_CACHE }}
        key: ${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
        restore-keys: |
          ${{ github.job }}-${{ strategy.job-index }}-

    - name: Install Mono dependencies
      if: inputs.include-mono == 'true'
      shell: bash
      run: |
        #Install Mono dependencies
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          echo "::group::Installing Linux Mono dependencies"
          sudo apt-get install -y \
          mono-devel
          echo "::endgroup::"
        fi
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "::group::Installing Windows Mono dependencies"
          winget install \
          mono-devel
          echo "::endgroup::"
        fi
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          echo "::group::Installing macOS Mono dependencies"
          brew install \
          mono-devel
          echo "::endgroup::"
        fi

    - name: Set Mono module enabled environment variable
      if: inputs.include-mono == 'true'
      shell: bash
      run: |
        #Set Mono module enabled environment variable
        echo "module_mono_enabled=module_mono_enabled=yes" >> $GITHUB_ENV

    - name: Build Rebel Editor for Mono
      if: inputs.include-mono == 'true'
      id: rebel-editor-for-mono
      uses: ./
      with:
        artifact: ${{ runner.os }}-rebel-editor-for-mono-glue
        build-options: ${{ env.module_mono_enabled }} mono_glue=no

    - name: Generate Mono Glue
      if: inputs.include-mono == 'true'
      shell: bash
      working-directory: RebelEngine
      run: |
        #Generate Mono Glue
        echo "::group::Generating Mono Glue"
        bin/${{ steps.rebel-editor-for-mono.outputs.build-filename }} --generate-mono-glue modules/mono/glue
        echo "::endgroup::"

    - name: Build Rebel
      shell: bash
      working-directory: RebelEngine
      run: |
        #Build Rebel
        echo "::group::Building Rebel"
        scons -j2 ${{ inputs.build-options }} ${{ env.module_mono_enabled }}
        echo "::endgroup::"

    - name: Get build filename
      id: get-build-filename
      shell: bash
      working-directory: RebelEngine/bin
      run: |
        #Get build filename
        echo "::group::Getting build filename"
        for file in *; do
          if [ -f "$file" ]; then
            if [[ $file == "rebel.windows"* ]]; then
              # Visual Studio creates additional files to support cross-linking
              if [[ $file != *".exe" ]]; then
                echo "Ignoring: $file"
                continue
              fi
            fi
            if [[ $file == "rebel.web"* ]]; then
              # Web builds contain multiple files that are put in the .zip file
              if [[ $file != *".zip" ]]; then
                echo "Ignoring: $file"
                continue
              fi
            fi
            echo "Build filename: $file"
            echo "filename=$file" >> $GITHUB_OUTPUT
          fi
        done
        echo "::endgroup::"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: RebelEngine/bin/
        retention-days: 1
